### ISSUE TITLE
Add artist and/or track autocomplete

### ISSUE THREAD

**Issue by crash7** [elamperti/OpenWebScrobbler#1]
Hi there,

It would be nice to have autocomplete for artist and/or tracks.
I think that [last.fm api](http://www.lastfm.es/api) methods are these:
- http://www.lastfm.es/api/show/artist.getSimilar
- http://www.lastfm.es/api/show/track.getSimilar

Let me know if you need help, i would be happy to contribute to this project.

**Comment by elamperti** [comment]
Thanks for your suggestion. It's something that could be useful if the response time is fast enough to actually help users. I'll look into it in the future, but feel free to contribute to the project. Your help is welcome.

Last.fm specifies in [their ToS](http://www.last.fm/api/tos) a maximum of "(...) 5 requests per originating IP address per second (...)"; other services may have similar limitations.

I added this suggestion to the wishlist on commit 1b2c7ff912f615bd818c62cac04fb0ea81d49e71

**Comment by dmelo** [comment]
Perhaps I can be of some help. I have developed a jquery plugin that uses CORS to directly query last.fm API and provide the autocomplete feature.

The project is at https://github.com/dmelo/lastfm-autocomplete

I will try an integration with OWS as soon as I get some free time.

**Comment by elamperti** [comment]
@dmelo that would be fantastic!

**Comment by dmelo** [comment]
I have implemented this and made the PR. I've put a live demo at http://ows.amuzi.me/

**Comment by elamperti** [comment]
Hi guys, I'll be closing this one for now. After the changes introduced in recent commits I think the scrobbler has a relatively complex UI and adding autocomplete would probably make for an overwhelming experience. Moreover, mobile users have predictive keyboards which may already taylor their input even better than we could.
However, I still think having autocomplete is a good idea and I'll revisit it once this new version is more rounded.
Thanks both of you, @crash7, @dmelo for your work and suggestions (and I'm glad it produced a fork with autocomplete implemented, as well!)
Cheers! :slightly_smiling_face:
