### ISSUE TITLE
Add album’s history

### ISSUE THREAD

**Issue by AntoineD-dot-fr** [elamperti/OpenWebScrobbler#122]
**Is your feature request related to a problem? Please describe**
I use this service to scrobble my vinyls.
It's a shame to always have to search for them when it's a limited collection.

**Describe the solution you'd like**
A history of the albums I scrobble would allow me in two click to re scrobble an album I have on vinyl.

**Describe alternatives you've considered**
It would be best if this list were ordered in order of last scrobble.
With why not the possibility of hiding certain albums that we would have listened to only once in another context.

**Additional context**

![Prototype idea](https://user-images.githubusercontent.com/1497894/85928777-f0628f00-b8af-11ea-860b-147d0a2e20be.png)

**Comment by elamperti** [comment]
Hi @Antoine-Derouin, thanks for this suggestion! I'll add it in the upcoming version :slightly_smiling_face:

**Comment by elamperti** [comment]
Wow, I'm so, so sorry I missed this. I think I had it in some branch and forgot about it. I've just added it and, to be extra sure, I've published it as well. It's available on versions 2.6.8 and up.

At the moment it will show the most recent albums you interacted with (i.e. albums that you opened on a previous search).

Thanks again for your idea and I hope you find it useful! ❤️
