### ISSUE TITLE
Time picker stays open when date picker is opened

### ISSUE THREAD

**Issue by ENDrain** [elamperti/OpenWebScrobbler#139]
**Describe the bug**
While setting custom timestamp, when date picker is opened, time picker does not close if was opened.

**Steps to reproduce**
1. Go to track scrobbler or an album tracklist
2. Click on "Custom timestamp"
3. Open the time picker
4. Open the date picker

**Expected behavior**
Time picker should close when date picker is opened.

**Screenshots**
![Снимок экрана 2021-04-23 185740](https://user-images.githubusercontent.com/29266283/115898119-dc52d400-a465-11eb-84c0-6b273fb8744f.jpeg)

**Device**
  * [x] Desktop
  * [ ] Mobile

**Platform (please complete the following information):**
 - Operating system: Windows_NT x64 10.0.19042
 - Browser: 87.0.4280.141
 - Version: v2.5.6

**Comment by elamperti** [comment]
This seems to be related with the issue described in #129 as well. The time picker will be upgraded in the next release, I'll make sure this doesn't happen with the new one. Thanks for raising the bug! (and sorry for the bad experience with the time picker)

**Comment by ENDrain** [comment]
Yeah the relation figures, I just thought I'd bring this specific issue up. Great job working on this app! I have a couple more bugs and suggestions, some might be still concerned with time picker 😅

**Comment by elamperti** [comment]
Fixed with 2.6.0!
