### ISSUE TITLE
Time picker is hard to close

### ISSUE THREAD

**Issue by ENDrain** [elamperti/OpenWebScrobbler#140]
**Describe the bug**
There are only two ways of closing time picker within the same page:

- `ESC` - only works if "TimePicker" input element (the one that you click to open the time picker pop-up) is still in focus
- Clicking the "TimePicker" input element again

**Steps to reproduce**
1. Go to track scrobbler or an album tracklist
2. Click on "Custom timestamp"
3. Open the time picker
4. Try any intuitive way of closing the time picker: click elswhere on page, start input in one of the fields, click on any button

**Expected behavior**
Time picker should close whenever it's obvious user interacts with something else on the page.

**Device**
  * [x] Desktop
  * [ ] Mobile

**Platform (please complete the following information):**
- Operating system: Windows_NT x64 10.0.19042
- Browser: 87.0.4280.141
- Version: v2.5.6

**Comment by elamperti** [comment]
Hi, thanks for taking the time to raise this issue! I agree the current time picker is not easy to close (or even use :sweat_smile:). I have a new time picker planned for the next version, I'll try to push it in the following days. I'll test this with the new one, hopefully it will be easier to use :)

**Comment by elamperti** [comment]
Hopefully the new time picker in 2.6.0 feels more intuitive :)
