### ISSUE TITLE
Time picker may be bugged into displaying wrong values

### ISSUE THREAD

**Issue by ENDrain** [elamperti/OpenWebScrobbler#141]
**Describe the bug**
Sometimes when picking time, if you enter value from keyboard in one of the fields and then click "increase" or "decrease" button for the same field, the TimePicker input element would update with wrong value for that field (namely, picker value +-1).

**Steps to reproduce**
- Go to track scrobbler or an album tracklist
- Click on "Custom timestamp"
- Open the time picker
- Choose one of the fields and enter a valid value from keyboard
- Click "increase" or "decrease" button for the same field
- See according value in the TimePicker element set to what's present in time picker +-1

**Expected behavior**
Values in time picker fields and TimePicker element should always match on update.

**Screenshots**
See **Additional context**

**Device**
  * [x] Desktop
  * [ ] Mobile

**Platform (please complete the following information):**
- Operating system: Windows_NT x64 10.0.19042
- Browser: 87.0.4280.141
- Version: v2.5.6

**Additional context**
I PROMISE I had this bug, but after refreshing the page I couldn't reproduce it! But I suppose this is worth mentioning anyway, maybe you could think of a way of failproofing this.

**Comment by elamperti** [comment]
The new time picker (2.6.0) doesn't present this issue! 👍🏼
