### ISSUE TITLE
Update TimePicker element automatically on keyboard input

### ISSUE THREAD

**Issue by ENDrain** [elamperti/OpenWebScrobbler#142]
**Is your feature request related to a problem? Please describe**
Currently, when you enter value in time picker from keyboard, you have to click elsewhere outside of an input field for the value in TimePicker element to update. This adds an extra step whenever I have to enter time manually.

**Describe the solution you'd like**
It would've been nice if TimePicker values updated with as few additional steps as possible after keyboard input in time picker.

**Describe alternatives you've considered**
- Update TimePicker on-the-fly with keyboard input from time picker
- Update TimePicker automatically after a delay once input is finished
- Allow updating TimePicker on `Enter`
- Allow updating TimePicker by clicking on the same input field (i.e. same as now but without having to move cursor)

**Comment by elamperti** [comment]
The new picker won't accept keyboard input, at least for now. Depending on user feedback I may add some keyboard alternative in the future, but I'll be focused on other features in the short term. Thanks for taking the time to voice your concern!
