### ISSUE TITLE
Timestamp inconsistency when scrobbling albums

### ISSUE THREAD

**Issue by ENDrain** [elamperti/OpenWebScrobbler#143]
**Is your feature request related to a problem? Please describe**
When scrobbling an album with "now" timestamp, timestamp acts as playback finish time, as in "what time did you finish listening to the album". This way, the timestamp is applied to the last song of the album, and the previous are moved earlier in time.

But, when scrobbling an album with custom timestamp, timestamp acts as playback start time, as in "what time did you start listening to the album". This way, the timestamp is applied to the first song of the album, and the next tracks are moved later in time.

**Describe the solution you'd like**
Timestamp should apply consistently when scrobbling albums and tracks, with "now" or custom timestamps, as the playback finish time.

**Comment by elamperti** [comment]
There's a ❓ where you can pick the timestamp which describes the decided behavior:

> Scrobbling tracks "now" will scrobble the last track at the current time, backdating the previous ones accordingly (as if you had just finished listening). The "custom timestamp" will define the timestamp of the first track and add time to the following tracks from there (i.e. you specify the time you started listening to this album)

Initially I thought about giving more options to user to pick how it should behave, but being as convoluted as it is, I chose to simplify it -knowing it may not be the favorite setting for all users-. It could be an _advanced_ setting, but it would also increase code complexity, so I'm not sure if it's worth the hassle.

**Comment by ENDrain** [comment]
Oh, so this is a feature... Honestly I can't see the motivation behind making timestamps behave differently at all.

**Comment by elamperti** [comment]
I'll keep this in mind for future enhancements, specially if I add some kind of "advanced settings" dialog. Thank you!
