### ISSUE TITLE
Broken website with LocalCDN add-on in Firefox

### ISSUE THREAD

**Issue by kibalcic** [elamperti/OpenWebScrobbler#155]
**Describe the bug**
OpenScrobbler site won't work with [LocalCDN](https://addons.mozilla.org/it/firefox/addon/localcdn-fork-of-decentraleyes/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) add-on in Firefox

**Steps to reproduce**
1. Install [LocalCDN](https://addons.mozilla.org/it/firefox/addon/localcdn-fork-of-decentraleyes/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) extension in Firefox
2. Go to https://openscrobbler.com
3. See error

**Device**
  *Desktop
  

**Platform (please complete the following information):**
 - Operating system (name and version): Windows 10, MacOS Catalina
 - Browser (name and version): Firefox 91
 - Version (see footer of website):

**Comment by elamperti** [comment]
Hi @kibalcic, this is something you should report to the extension maintainers, as it's a third-party modification on the site.

We use a CDN to improve loading speeds and reduce bandwidth. 

A quick fix for you could be disabling the extension for this particular website (you can still manage and fine-tune external requests with uBlock), although I can imagine it's not what you want.
