### ISSUE TITLE
Don't show empty albums

### ISSUE THREAD

**Issue by eduard-bystrov** [elamperti/OpenWebScrobbler#167]
![image](https://user-images.githubusercontent.com/34031317/151370901-ea23cb03-0cfe-496e-aaeb-ef04e80a572e.png)

it makes no sense. There is nothing to scrobble in them

**Comment by elamperti** [comment]
Hi @eduard-bystrov, thanks for your report. This is a problem coming from the Last.fm API, not the scrobbler itself. I reported it almost two years ago and there's no clear timeline for a solution ([thread](https://support.last.fm/t/bug-some-albums-return-an-empty-track-array-even-if-they-show-tracks-in-last-fm/2030/4)).

You can switch the data source to Discogs instead, which should solve this problem for you (from the top-right menu -> settings -> change the data source to _Discogs_ and save, then search again for the album you want).

FYI I have a plan to improve this situation either in the upcoming revision or with the next big update (defaulting to Discogs and changing the application flow around album search). The immediate solution is just switching the data source to Discogs.
