### ISSUE TITLE
The Next Button seems to be having some issues

### ISSUE THREAD

**Issue by pmcdonough8133** [elamperti/OpenWebScrobbler#175]
When I click 'Next' on the scrobble another user to try and open scrobble something that was scrobbled beyond the last 50 scrobbles, it refreshes the list like it moved to the next page but it stays on the current list of 50 scrobbles.  User I've been testing on: https://openscrobbler.com/scrobble/user/IAmThBlackMetal

**Comment by elamperti** [comment]
Hi, thanks for reporting this issue! I'll be working on it today, should be a quick fix. I'll keep you updated.

**Comment by elamperti** [comment]
@pmcdonough8133 The issue was fixed in v2.6.6, which has been published some minutes ago. I've also added better pagination (with numbered pages) so it should be even better than before :)

**Comment by pmcdonough8133** [comment]
Much appreciated! Looking forward to using it again
