### ISSUE TITLE
Results with relases included link to release with id of master of actual result

### ISSUE THREAD

**Issue by LeviOP** [elamperti/OpenWebScrobbler#187]
**Describe the bug**
When searching for albums with "Include releases in search results" checked, the resulting albums all link to `/scrobble/album/view/dsid/release-{master id of actual album}` instead of the actual result's release id.

**Steps to reproduce**

1. Open https://openscrobbler.com/scrobble/album
2. Ensure that your data source is set to "Discogs"
3. Toggle the switch labeled "Include releases in search results" into the on position
4. Search for an album (For example I will use the term "Madvillainy")
5. Click on the "Search" button
6. Click on any of the results.
7. Observe that the album is not the one you clicked on.
8. Look at the URL
In the case of "Madvillainy", the results all link to "release-8554", which is in fact not a release of this album, but instead the master id of this album. This means that the resulting album will be some random release that happens to have the same id as the master id.
For reference:
Madvillainy's master (master id 8554): https://www.discogs.com/master/8554-Doom-And-Madlib-Madvillain-Madvillainy
"Trip Through Sound", a random release with a matching id (release id 8554): https://www.discogs.com/release/8554-Various-Trip-Through-Sound

**Expected behavior**
I would expect that the album I clicked on actually appears, taking me to a link with the correct release.

**Screenshots**
![image](https://user-images.githubusercontent.com/35459268/191606925-460e04d9-4b60-4580-a214-a6e889470116.png)
![image](https://user-images.githubusercontent.com/35459268/191606961-d5188b43-61c9-4774-822c-7f3852c06e3c.png)

**Device**
  * [x] Desktop
  * [ ] Mobile

**Platform (please complete the following information):**
 - Operating system (name and version): Windows 10 Home version 21H2 build 19044.2006
 - Browser (name and version): Firefox 104.0.2 (64-bit)
 - Version (see footer of website): 2.6.9

**Additional context**

**Comment by elamperti** [comment]
I appreciate your detailed report, it was very easy to follow and reproduce 😃 
This bug will be fixed on versions 2.6.10 and up (I'll release it today)
Thank you!
