### ISSUE TITLE
Last.fm search results not shown

### ISSUE THREAD

**Issue by chrisjmoss** [elamperti/OpenWebScrobbler#220]
**Describe the bug**
I've been experiencing this bug for a number of weeks. 

When I use the album search and use the "Search on Last.fm" option, I briefly see the Last.fm results flash up, before it gives me the Discogs results. This is happening on both an iPhone using Safari and a macbook using Chrome. 

**Steps to reproduce**
1. Go to "Scrobble album" page.
2. Paste an album title into the search bar but do not click search yet e.g. "Come Together (Adventures On The Indie Dancefloor 1989-1992)" 
3. Click on the green dropdown to change the search type from Discogs to Last.fm.
4. Click search. 
6. You will see the Last.fm results briefly flash up, before it gives you the Discogs results. In the example above, there will be no albums found, because the spelling on Discogs is slightly different  

**Expected behavior**
I'd expect to see the Last.fm search results

**Screenshots**
If applicable, add screenshots to help explain your problem (link them or drag and drop them into the issue to upload)

**Device**
  * Macbook - Chrome
  * iPhone - Safari

**Platform (please complete the following information):**
 - Operating system (name and version): iOS 16.3.1
 - Browser (name and version): Safari 
 - Version (see footer of website): v2.7.11

**Additional context**

**Comment by elamperti** [comment]
Hi, thanks for filing this bug report. Sorry for the inconvenience! I've been trying to reproduce it following your information but I'm not getting Discogs results (these are from lastfm):
![Screenshot 2023-10-16 Open Scrobbler](https://github.com/elamperti/OpenWebScrobbler/assets/910672/79b23ed3-a6f8-47fd-9d65-77a8a7f70968)

Can you try this?
- Reset the scrobbler state by using [this link](https://openscrobbler.com/reset.html) (don't worry, your last.fm account isn't affected!)
- Sign in again and try to reproduce the issue

Let me know if this solves the issue or if it stays the same. If the bug keeps happening, it would be useful to have a few more album search examples. Thank you!

**Comment by chrisjmoss** [comment]
Hi @elamperti, thanks for the suggestion. Unfortunately it has not fixed it. Here's a Loom video of it happening:

https://www.loom.com/share/8f8eb185e7174445a256475875ac3376?sid=d2d5f39a-6a66-4264-9d8d-853bcbd828b6

This happens for ALL albums searches. Other examples:

- "London Calling (Remastered)"
- "A Monstrous Psychedelic Bubble"

Thanks.

**Comment by elamperti** [comment]
Thanks for the Loom video, it's helpful. I'm still trying to figure out this issue. Even though I wasn't able to reproduce it in Mac+Chrome or iOS+Safari, I found some evidence in logs that may be related to this and help solving it (ref. OPENSCROBBLER-7Q).  I've also verified the settings stored for your last.fm user and it's all ok on that side.

It's probably an error that's invalidating the incoming data or the local storage. 

I'll let you know if I find a fix or any other relevant information.

**Comment by elamperti** [comment]
Hi Chris, I was finally able to reproduce, track down, and fix this bug. 
The fix will be available on version 2.8.0, which I'll be releasing soon :)

<details>
<summary>More info: Cause of this bug</summary>
It was caused by the application reloading the settings while it fetched the albums' data, which in turn modified the selected provider (lastfm), causing the site to perform a second album search on the alternate provider (discogs), overriding the first set of results.
The bug was hard to track down because it originated in an unrelated code section (authentication) and also required users to perform a search on lastfm with their preferred provider in settings set to discogs.
</details>

**Comment by elamperti** [comment]
Hi again Chris, thanks for your patience over these weeks. I've released version 2.8.0 with the fix. It should solve this issue, but feel free to reopen this issue if you still need help!
