### ISSUE TITLE
Parse song info from last.fm url

### ISSUE THREAD

**Issue by codythecoder** [elamperti/OpenWebScrobbler#221]
**Is your feature request related to a problem? Please describe**
When pasting in the format `Artist Name - Song Title` you get the message `The pasted text was automatically split!` which is a wonderfully convenient feature. I'd love similar functionality for if you paste a last.fm URL

**Describe the solution you'd like**
The most straightforward solution to this would be to take the url (e.g. `https://www.last.fm/music/chelmico/_/ISOGA%E2%99%A1PEACH`) and parse the artist and song title from this (after url-decoding it (example related)).

**Describe alternatives you've considered**
There's a possibility to also get the album the song is from via the API - but I think this would produce unclear results in cases where a song belongs to more than one album. (and also be more work than it's worth)

**Additional context**
If people think this is a good idea I'd be happy to do this myself and create a PR

**Comment by elamperti** [comment]
I think this one could be easy to implement on the current code, feel free to create a PR for it!

Hint: `catchPaste()` in SongForm component.

**Comment by andrewarosario** [comment]
This is a pretty good idea. I'll code it :)
