### ISSUE TITLE
Footer overlaps language drop-down list

### ISSUE THREAD

**Issue by fitojb** [elamperti/OpenWebScrobbler#232]
On Firefox, the bottommost elements of the language list aren't reachable as the page's footer overlaps them.
![imagen](https://github.com/elamperti/OpenWebScrobbler/assets/554953/f3ad8768-1705-409f-b0e1-d0a485c2f7ca)

**Comment by elamperti** [comment]
Hi Adolfo, thanks for bringing up this issue! I've made a few adjustments; the fix will be available on the next release. Thank you!
