### ISSUE TITLE
24h format doesn't apply

### ISSUE THREAD

**Issue by jetdzhet** [elamperti/OpenWebScrobbler#254]
**Describe the bug**
The 24h format doesn't apply to the site, even if I disable the "Use 12-hour time format" option.

**Steps to reproduce**
1. Disabling the "Use 12-hour time format" option in Settings.
2. Click on the "Custom..." button in the Timestamp section.
3. Try to type any other number more than 12 (for example, 15) in the hour part. (Or pressing the clock button in the left side, which is actually shown in 24 hour format.)
4. The 15 hour part changes to 03.
5. If I press the scrobble button, the song is scrobbled at 3 AM.

**Expected behavior**
When I type 15 in the timestamp, it should remain as 15, and scrobble the song with the 3 PM timestamp.

**Device**
  * Desktop
 
**Platform (please complete the following information):**
 - Operating system (name and version): Windows 11 24H2 (64 bits)
 - Browser (name and version): Firefox Developer Edition version 134.0b8
 - Version (see footer of website): v2.9.0

**Additional context**
I have already tried checking the time format of Windows, it is correctly set in 24 hour time format I also tried using the website with Firefox troubleshoot mode and the issue persists. This doesn't happen in Microsoft Edge or mobile versions of Firefox, though.

**Comment by elamperti** [comment]
Hi, thanks for reporting this issue! I haven't been able to reproduce it using Firefox (stable, v133). 

It may have something to do with your browser version as well, the _developer_ variant (which as far as I see stems from the beta version) and/or its configuration.

---

In this test, using Firefox (using `en-US` locale, as the locale determines the format of the input, regardless of the language you pick in Open Scrobbler or the 12-hour setting), I started with a 5:30 AM timestamp:
![image](https://github.com/user-attachments/assets/996f9cee-1aa7-4e91-8197-4ae6a441c277)

Then I entered `14` in the hours' part of the time, and it properly changed not only the hour (`02`) but also the AM/PM indicator (now it's `PM`):
![image](https://github.com/user-attachments/assets/baba9c4e-3f30-42d8-9a3c-fc6955b4d4a7)

Out of curiosity, what locale(s) are you using? (you can get a list of them from the console in any browser tab (F12) by entering `navigator.languages`)

**Comment by jetdzhet** [comment]
I am using "es-MX" locale, 
It has passed a few weeks since then and the web's behaviour has changed. Now it behaves the way you describe it.

**Comment by elamperti** [comment]
Great, I'm glad to know it's working as expected now! 🎉  I'll close this issue for now. 

Feel free to re-open it if you experience this issue again, and we'll try to figure it out :)
