### ISSUE TITLE
Allow users to enter album artist name

### ISSUE THREAD

**Issue by ghost** [elamperti/OpenWebScrobbler#32]
Hi! You made a great scrobbler, but it could be amazing if you add the Album Artist tag. This tag is necessary when you need to scrobble an album with multiple artists on it (for example, a soundtrack album). The Universal Scrobbler supports this feature, and I hope the Open Web Scrobbler will support it too.
Thank you in advance.

**Comment by elamperti** [comment]
@manuesperon FYI, this is finally implemented :blush:
