### ISSUE TITLE
Soundcloud

### ISSUE THREAD

**Issue by rhodesm4** [elamperti/OpenWebScrobbler#35]
Does this work for soundcloud?

**Comment by elamperti** [comment]
Hi @rhodesm4, this is a manual scrobbler, regardless of where you are listening to a song you have to enter the song information yourself and submit it. See [the working website](https://ows.elamperti.com/) to check how it works. There are extensions that may scrobble automatically for you if that's what you are looking for, though I'm not aware of which of the existing ones does it (you'll have to search and experiment).

There's a good community of last.fm users at reddit ([/r/lastfm](https://www.reddit.com/r/lastfm), they may be able to help you better than me on that aspect 😄
