### ISSUE TITLE
Being signed out 

### ISSUE THREAD

**Issue by JabyPearl** [elamperti/OpenWebScrobbler#36]
Love this site so much, so thank you! But lately I'm having to re-authorize it every few minutes. If I leave the page idle for more than a few minutes, I have to refresh the page and log back in with my Lastfm account. Again, really appreciate all the work you've put in this.

**Comment by elamperti** [comment]
@JabyPearl hey, thanks for letting me know. I recently moved to a new server and this seems to be related to #27. I changed some settings on `php.ini`, let's see how that goes. It may require you to log in one more time, but after that you should be good. I'll be monitoring this. Thanks again!

**Comment by elamperti** [comment]
My session is alive since the change, I believe it's fixed. Let me know if there's any problem! For now I'll consider this solved :)
