### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by IBlackened** [elamperti/OpenWebScrobbler#37]
First of all, thank you for this manual scrobbler. It's quite useful for me, that's why I created this account just to post this, but I can't access the site. Firefox says the certificate expired on March 22nd and I can't add an exception to it. I tried running it in www.ssllabs.com and it says the same thing, so it's probably not happening just with me.

**Comment by elamperti** [comment]
@IBlackened hi, thanks for taking the time to create an account and report this issue!

You are correct: the certificate was expired; I forgot to renew it. My bad!
Now it should be working fine.

Sorry for the inconvenience!
Have a great day :)

**Comment by IBlackened** [comment]
@elamperti  - Reading it again, I may have sounded like an entitled prick, but that was not my intention. I was trying to say that I'm really grateful for the site. I use it almost daily, and now it's working! :D

Thank you very, very much!

**Comment by elamperti** [comment]
@IBlackened not at all, and I'm glad you took the time to report the issue. Thanks once again!
