### ISSUE TITLE
Scrobble tracks from another user

### ISSUE THREAD

**Issue by elamperti** [elamperti/OpenWebScrobbler#5]
This should be easy to implement using the API and multiple scrobbling.

See: http://www.last.fm/api/show/user.getRecentTracks

**Comment by dfmv2018** [comment]
how to make this work?

**Comment by elamperti** [comment]
Hi @dfmv2018, this is not implemented yet! Sorry about that 😞

**Comment by dfmv2018** [comment]
the only way i can do this is truly universalscrobbler?
so unfair to have to pay for this

**Comment by elamperti** [comment]
@dfmv2018 That's an alternative for now. I'll let you know when this is implemented, but it will probably take some time, as this is a side-project I maintain on my spare time. The Open Web Scrobbler (and even the paid universalscrobbler) are not related with last.fm, we are just providing a service to the community.

In the case of this particular project, it's an open source initiative to which you may contribute with code (or patience/understanding in the meantime 😁).
Thanks for voicing your interest in this feature!

**Comment by elamperti** [comment]
Implemented on 5f49dc6d :fireworks: 

@dfmv2018 now it's [live on the site](https://openscrobbler.com/)! I hope it helps you.
