### ISSUE TITLE
allowing users to change the language in two different spots produces a bug

### ISSUE THREAD

**Issue by lyramsr** [elamperti/OpenWebScrobbler#55]
it's like when you have two light switches that control one light. when you turn one on, the other remains unchanged.

e.g. when I set the language to polish in the setting menu, the site turns polish. if I then set it to dutch in the dropdown on the top right of the page, it turns dutch. but then if I go back to the settings menu, the menu says "polish", even though the site is set to dutch. if I then save the settings without changing the option in the menu to dutch, it goes back to polish.

**Comment by lyramsr** [comment]
idk if I explained that well—point is, I'm not sure why there are two locations where it can be changed. the option in the top right would do fine I reckon

**Comment by elamperti** [comment]
The original idea was that you could set a language for your user from settings, and temporarily change it for the current browser from the :globe_with_meridians: icon. In practice it resulted in a poor UX choice, and I plan to unify both so wherever you set a language with a logged in user, the selected language will be saved.
