### ISSUE TITLE
Allow a custom timestamp

### ISSUE THREAD

**Issue by elamperti** [elamperti/OpenWebScrobbler#7]
Allow a custom timestamp so users can pick at what time they listened to a song.

**Comment by elamperti** [comment]
It would be useful to have a friendly time picker.

**Comment by elamperti** [comment]
@crash7 thanks for your contribution!

**Comment by elamperti** [comment]
Made the timestamp optional using a checkbox (see commit ca4506263744d82928b38ee730d5f10abf96373e). It's rough but it'll be enough for now.

**Comment by crash7** [comment]
@elamperti this can be closed, right?

**Comment by elamperti** [comment]
@crash7 I'll close this issue once we add a timepicker and enable it for the users (soon!)

**Comment by elamperti** [comment]
Solved after PR #22
