### ISSUE TITLE
User gets kicked out accessing "Your profile" tab

### ISSUE THREAD

**Issue by elamperti** [elamperti/OpenWebScrobbler#93]
**Describe the bug**
When a user clicks on "your profile" from the manual scrobbling page, it gets kicked out if their recent tracks are private.

**Steps to reproduce**
1. In last.fm, go to settings and enable "hide recent listening information"
2. From the scrobbler, go to the manual scrobbling page, and click in "Your profile"
3. You'll be logged out and redirected to the home with the _authNeeded_ error

**Expected behavior**
The profile should be shown or listed as unavailable, and the user must remain logged in.

**Screenshots**
![Screenshot](https://media.discordapp.net/attachments/474201109985099777/588951730537103360/lastfm_open_scrobbler.gif)

**Device**
  * [x] Desktop
  * [x] Mobile

**Platform (please complete the following information):**
 - Operating system (name and version): Any
 - Browser (name and version): Firefox (any)
 - Version (see footer of website): 2.4.7

**Additional context**
Reported by asmLANG through Discord (thanks!)

**Comment by elamperti** [comment]
To do:
  - [ ] Catch the empty/failing response. Show a tip to the user about what happens.
  - [ ] Verify if the scrobbler is signing the request as the current user
    - [ ] If so, report issue to last.fm

**Comment by thomasbnt** [comment]
Same bug :(

**Comment by elamperti** [comment]
This has been fixed (from last.fm side) for users trying to view their own profile. An upcoming fix will deal with OWS kicking out the user accidentally if it happens again :+1:

**Comment by elamperti** [comment]
Fixed in 6b1435f
